# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SerialHelper_gui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1055, 635)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalGroupBox = QtWidgets.QGroupBox(Form)
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.verticalGroupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.gridLayout_3.addWidget(self.s2__receive_text, 0, 0, 4, 1)
        self.hex_receive = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.hex_receive.setObjectName("hex_receive")
        self.gridLayout_3.addWidget(self.hex_receive, 0, 1, 1, 1)
        self.s3__send_text = QtWidgets.QTextEdit(self.verticalGroupBox)
        self.s3__send_text.setObjectName("s3__send_text")
        self.gridLayout_3.addWidget(self.s3__send_text, 0, 2, 3, 3)
        self.hex_send = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.hex_send.setObjectName("hex_send")
        self.gridLayout_3.addWidget(self.hex_send, 0, 5, 1, 1)
        self.s2__clear_button = QtWidgets.QPushButton(self.verticalGroupBox)
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.gridLayout_3.addWidget(self.s2__clear_button, 1, 1, 1, 1)
        self.s3__send_button = QtWidgets.QPushButton(self.verticalGroupBox)
        self.s3__send_button.setObjectName("s3__send_button")
        self.gridLayout_3.addWidget(self.s3__send_button, 1, 5, 1, 1)
        self.s3__clear_button = QtWidgets.QPushButton(self.verticalGroupBox)
        self.s3__clear_button.setObjectName("s3__clear_button")
        self.gridLayout_3.addWidget(self.s3__clear_button, 2, 5, 1, 1)
        self.timer_send_cb = QtWidgets.QCheckBox(self.verticalGroupBox)
        self.timer_send_cb.setObjectName("timer_send_cb")
        self.gridLayout_3.addWidget(self.timer_send_cb, 3, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalGroupBox)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 3, 3, 1, 1)
        self.dw = QtWidgets.QLabel(self.verticalGroupBox)
        self.dw.setObjectName("dw")
        self.gridLayout_3.addWidget(self.dw, 3, 4, 1, 2)
        self.PyqtgraphWorkspace = QtWidgets.QVBoxLayout()
        self.PyqtgraphWorkspace.setObjectName("PyqtgraphWorkspace")
        self.gridLayout_3.addLayout(self.PyqtgraphWorkspace, 4, 0, 1, 6)
        self.gridLayout_2.addWidget(self.verticalGroupBox, 0, 1, 1, 1)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setObjectName("formGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.formGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.gridLayout.addWidget(self.s1__lb_5, 4, 0, 1, 1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.gridLayout.addWidget(self.s1__box_1, 0, 1, 1, 1)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.gridLayout.addWidget(self.s1__lb_4, 3, 0, 1, 1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.gridLayout.addWidget(self.s1__lb_2, 1, 0, 1, 1)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.gridLayout.addWidget(self.s1__lb_6, 5, 0, 1, 1)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.gridLayout.addWidget(self.s1__box_3, 2, 1, 1, 1)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.gridLayout.addWidget(self.s1__box_5, 4, 1, 1, 1)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setObjectName("close_button")
        self.gridLayout.addWidget(self.close_button, 7, 0, 1, 1)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.gridLayout.addWidget(self.s1__lb_3, 2, 0, 1, 1)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.gridLayout.addWidget(self.s1__box_4, 3, 1, 1, 1)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.gridLayout.addWidget(self.s1__box_2, 1, 1, 1, 1)
        self.formGroupBox1 = QtWidgets.QGroupBox(self.formGroupBox)
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox1)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formGroupBox1)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.formGroupBox1)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.gridLayout.addWidget(self.formGroupBox1, 8, 0, 1, 1)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.gridLayout.addWidget(self.s1__box_6, 5, 1, 1, 1)
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.gridLayout.addWidget(self.s1__lb_1, 0, 0, 1, 1)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setObjectName("open_button")
        self.gridLayout.addWidget(self.open_button, 6, 0, 1, 1)
        self.gridLayout_2.addWidget(self.formGroupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.verticalGroupBox.setTitle(_translate("Form", "接受区"))
        self.hex_receive.setText(_translate("Form", "Hex接收"))
        self.s3__send_text.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">123456</span></p></body></html>"))
        self.hex_send.setText(_translate("Form", "Hex发送"))
        self.s2__clear_button.setText(_translate("Form", "清除"))
        self.s3__send_button.setText(_translate("Form", "发送"))
        self.s3__clear_button.setText(_translate("Form", "清除"))
        self.timer_send_cb.setText(_translate("Form", "定时发送"))
        self.lineEdit_3.setText(_translate("Form", "1000"))
        self.dw.setText(_translate("Form", "ms/次"))
        self.formGroupBox.setTitle(_translate("Form", "串口设置"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__box_3.setItemText(0, _translate("Form", "115200"))
        self.s1__box_3.setItemText(1, _translate("Form", "2400"))
        self.s1__box_3.setItemText(2, _translate("Form", "4800"))
        self.s1__box_3.setItemText(3, _translate("Form", "9600"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "230400"))
        self.s1__box_3.setItemText(11, _translate("Form", "460800"))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.s1__lb_3.setText(_translate("Form", "波特率："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.formGroupBox1.setTitle(_translate("Form", "串口状态"))
        self.label.setText(_translate("Form", "已接收："))
        self.label_2.setText(_translate("Form", "已发送："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.open_button.setText(_translate("Form", "打开串口"))

